
    <?php
$text='<p style="text-align: right;"><i><span style="font-weight: 400;">Barbadhal,<br>
</span></i><i><span style="font-weight: 400;">le 19/01/23</span></i></p>
<p><i><span style="font-weight: 400;">Cher neveu,</span></i></p>
<p><i><span style="font-weight: 400;">Si tu lis cette lettre, c’est que je l’ai écrite…</span></i></p>
<p><i><span style="font-weight: 400;">J</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> n</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> pouv</span></i><b><i>a</i></b><i><span style="font-weight: 400;">is m</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> résign</span></i><b><i>e</i></b><i><span style="font-weight: 400;">r à p</span></i><b><i>a</i></b><i><span style="font-weight: 400;">r</span></i><b><i>le</i></b><i><span style="font-weight: 400;">r </span></i><b><i>de</i></b><i><span style="font-weight: 400;"> c</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> qu</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> j’</span></i><b><i>a</i></b><i><span style="font-weight: 400;">i vu. C</span></i><b><i>e</i></b><i><span style="font-weight: 400;">tt</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> myri</span></i><b><i>ade</i></b> <b><i>de</i></b><i><span style="font-weight: 400;"> cou</span></i><b><i>le</i></b><i><span style="font-weight: 400;">urs </span></i><b><i>a</i></b><i><span style="font-weight: 400;">ur</span></i><b><i>a</i></b><i><span style="font-weight: 400;">it r</span></i><b><i>e</i></b><i><span style="font-weight: 400;">n</span></i><b><i>d</i></b><i><span style="font-weight: 400;">u fou n’import</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> qu</span></i><b><i>el</i></b> <b><i>e</i></b><i><span style="font-weight: 400;">xp</span></i><b><i>l</i></b><i><span style="font-weight: 400;">or</span></i><b><i>a</i></b><i><span style="font-weight: 400;">t</span></i><b><i>e</i></b><i><span style="font-weight: 400;">ur, </span></i><b><i>e</i></b><i><span style="font-weight: 400;">t j</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> m</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> suis sorti </span></i><b><i>de</i></b><i><span style="font-weight: 400;"> c</span></i><b><i>e</i></b><i><span style="font-weight: 400;">t </span></i><b><i>e</i></b><i><span style="font-weight: 400;">n</span></i><b><i>d</i></b><i><span style="font-weight: 400;">roit </span></i><b><i>de</i></b><i><span style="font-weight: 400;"> just</span></i><b><i>e</i></b><i><span style="font-weight: 400;">ss</span></i><b><i>e</i></b><i><span style="font-weight: 400;">.</span></i></p>
<p><i><span style="font-weight: 400;">J</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> suis r</span></i><b><i>e</i></b><i><span style="font-weight: 400;">p</span></i><b><i>a</i></b><i><span style="font-weight: 400;">rti </span></i><b><i>a</i></b><i><span style="font-weight: 400;">v</span></i><b><i>e</i></b><i><span style="font-weight: 400;">c un coffr</span></i><b><i>e</i></b><i><span style="font-weight: 400;">t cont</span></i><b><i>e</i></b><i><span style="font-weight: 400;">n</span></i><b><i>a</i></b><i><span style="font-weight: 400;">nt un s</span></i><b><i>e</i></b><i><span style="font-weight: 400;">cr</span></i><b><i>e</i></b><i><span style="font-weight: 400;">t sur </span></i><b><i>le</i></b><i><span style="font-weight: 400;">s origin</span></i><b><i>e</i></b><i><span style="font-weight: 400;">s </span></i><b><i>de</i></b><i><span style="font-weight: 400;"> c</span></i><b><i>e</i></b><i><span style="font-weight: 400;">rt</span></i><b><i>a</i></b><i><span style="font-weight: 400;">in</span></i><b><i>e</i></b><i><span style="font-weight: 400;">s cités. C</span></i><b><i>elle</i></b><i><span style="font-weight: 400;">s </span></i><b><i>a</i></b><i><span style="font-weight: 400;">u cœur </span></i><b><i>de</i></b> <b><i>L</i></b><i><span style="font-weight: 400;">‘H</span></i><b><i>e</i></b><i><span style="font-weight: 400;">x</span></i><b><i>a</i></b><i><span style="font-weight: 400;">gon</span></i><b><i>e</i></b> <b><i>de</i></b><i><span style="font-weight: 400;">s B</span></i><b><i>e</i></b><i><span style="font-weight: 400;">r</span></i><b><i>l</i></b><i><span style="font-weight: 400;">u</span></i><b><i>de</i></b><i><span style="font-weight: 400;">s, c</span></i><b><i>e</i></b> <b><i>l</i></b><i><span style="font-weight: 400;">i</span></i><b><i>e</i></b><i><span style="font-weight: 400;">u où </span></i><b><i>d</i></b><i><span style="font-weight: 400;">isp</span></i><b><i>a</i></b><i><span style="font-weight: 400;">r</span></i><b><i>a</i></b><i><span style="font-weight: 400;">iss</span></i><b><i>e</i></b><i><span style="font-weight: 400;">nt b</span></i><b><i>ea</i></b><i><span style="font-weight: 400;">ucoup </span></i><b><i>d</i></b><i><span style="font-weight: 400;">‘</span></i><b><i>a</i></b><i><span style="font-weight: 400;">éron</span></i><b><i>e</i></b><i><span style="font-weight: 400;">fs.</span></i></p>
<p><i><span style="font-weight: 400;">J’</span></i><b><i>a</i></b><i><span style="font-weight: 400;">i </span></i><b><i>e</i></b><i><span style="font-weight: 400;">nf</span></i><b><i>e</i></b><i><span style="font-weight: 400;">rmé c</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> s</span></i><b><i>e</i></b><i><span style="font-weight: 400;">cr</span></i><b><i>e</i></b><i><span style="font-weight: 400;">t à </span></i><b><i>l</i></b><i><span style="font-weight: 400;">‘</span></i><b><i>e</i></b><i><span style="font-weight: 400;">n</span></i><b><i>d</i></b><i><span style="font-weight: 400;">roit où t</span></i><b><i>e</i></b><i><span style="font-weight: 400;">s bi</span></i><b><i>e</i></b><i><span style="font-weight: 400;">ns sont r</span></i><b><i>a</i></b><i><span style="font-weight: 400;">ngés. Souvi</span></i><b><i>e</i></b><i><span style="font-weight: 400;">ns-toi </span></i><b><i>de la</i></b><i><span style="font-weight: 400;"> tr</span></i><b><i>a</i></b><i><span style="font-weight: 400;">pp</span></i><b><i>e</i></b> <b><i>a</i></b><i><span style="font-weight: 400;">u c</span></i><b><i>ade</i></b><i><span style="font-weight: 400;">n</span></i><b><i>a</i></b><i><span style="font-weight: 400;">s qu</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> j</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> n</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> t</span></i><b><i>e</i></b> <b><i>la</i></b><i><span style="font-weight: 400;">iss</span></i><b><i>a</i></b><i><span style="font-weight: 400;">is p</span></i><b><i>a</i></b><i><span style="font-weight: 400;">s ouvrir. Tu n’</span></i><b><i>a</i></b><i><span style="font-weight: 400;">s qu’à trouv</span></i><b><i>e</i></b><i><span style="font-weight: 400;">r </span></i><b><i>le</i></b><i><span style="font-weight: 400;"> co</span></i><b><i>de</i></b><i><span style="font-weight: 400;"> pour </span></i><b><i>a</i></b><i><span style="font-weight: 400;">ccé</span></i><b><i>de</i></b><i><span style="font-weight: 400;">r à c</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> s</span></i><b><i>e</i></b><i><span style="font-weight: 400;">cr</span></i><b><i>e</i></b><i><span style="font-weight: 400;">t. Tu t’</span></i><b><i>e</i></b><i><span style="font-weight: 400;">n f</span></i><b><i>a</i></b><i><span style="font-weight: 400;">is p</span></i><b><i>a</i></b><i><span style="font-weight: 400;">s, c’</span></i><b><i>e</i></b><i><span style="font-weight: 400;">st un co</span></i><b><i>de</i></b><i><span style="font-weight: 400;"> énorm</span></i><b><i>e</i></b><i><span style="font-weight: 400;">, pour </span></i><b><i>d</i></b><i><span style="font-weight: 400;">écour</span></i><b><i>a</i></b><i><span style="font-weight: 400;">g</span></i><b><i>e</i></b><i><span style="font-weight: 400;">r </span></i><b><i>le</i></b><i><span style="font-weight: 400;">s curi</span></i><b><i>e</i></b><i><span style="font-weight: 400;">ux.</span></i></p>
<p><i><span style="font-weight: 400;">J</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> t</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> confi</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> c</span></i><b><i>e</i></b><i><span style="font-weight: 400;"> s</span></i><b><i>a</i></b><i><span style="font-weight: 400;">voir !</span></i></p>
<p style="text-align: right;"><i><span style="font-weight: 400;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></i> <i><span style="font-weight: 400;">Louis Armand Danot Ermiste</span></i></p>
<p><i><span style="font-weight: 400;">&nbsp;</span></i><i><span style="font-weight: 400;">P.S :</span></i><i><span style="font-weight: 400;"> Le gras, c’est la vie !</span></i></p>';
$text=strip_tags($text,'<b>'); 
echo htmlspecialchars($text);
$pieces = explode("<b>", $text);
var_dump($pieces);
$text=strstr($text,'<br>');
$text= explode("<b>",$text);
foreach($text as &$pieces){
    $pieces=str_replace(" ","",strstr($pieces, "</br>", true));
}
$e= strtolower (implode ($text));
print_r($text);
foreach (count_chars($pieces, 1) as $i => $val) {
   echo chr($i).": ". $val."<br>";
}
//$hex = hex2bin("312B3F3D38");
//var_dump($hex);
//$a="31 2B 3F 3D 38";
//echo hex2bin(strtr($a,[" "=>""]));
//echo"<br>";

?>

    